### ISSUE TITLE
Portfolio Feedback Week 4

### ISSUE THREAD

**Issue by alexandraiov** [w201rdada/portfolio-subhap15#1]
Gist: Create a device that will monitor what is in a pantry, including the amount and expiration dates. This information would then help users figure out what to cook, what to purchase, where to compost. 

Kept: I like most parts of the proposal. I would cut a couple sections (see below), but everything else should be kept.

Cut: The home composting part and the donations part didn't seem to fit in with the product. I'm not sure how this iOT device will help the user create a home garden or restaurants donate leftovers. I like that it would show users where composting sites are nearby.

Rearranged: I think it is well arranged.

Added: I would like to know more about the device. And I would like to see something about the downside, like installation or cost hurdles.

Comments: This is a really cool idea! Thanks for sharing.

**Comment by subhap15** [comment]
Thanks for your feedback. I have removed restaurants and for now focusing on consumers being the end user. Also, to your other point regarding more info about the device, I have added a section to talk about ecosystem. Thanks!
